title: Improvement of Pasture Mapping in the Cerrado Biome — WRI Brasil & LAPIG/UFG
description: Detailed Sampling Plan and Multi-Stage Sample Curation for Cerrado Pastures (2020–2025) — WRI Brasil, FUNAPE & LAPIG/UFG
baseurl: "/lapig-wribrasil"
url: "https://lapig-ufg.github.io"
