title: Improvement of Pasture Mapping in the Cerrado Biome — WRI Brasil & LAPIG/UFG
description: Detailed Sampling Plan, Spectral Embeddings (Sentinel-2 10 m), and Multi-Stage Sample Curation for Cerrado Pastures (2020–2025) — WRI Brasil, FUNAPE, LAPIG/UFG & Embrapa Cenargen
baseurl: "/lapig-wribrasil"
url: "https://lapig-ufg.github.io"
